apiVersion: v1
kind: ServiceAccount
metadata:
  name: ken
  namespace: dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jane-role-binding
subjects:
  - kind: ServiceAccount
    name: jane
    namespace: dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view

