repositories:
  - name: stable
    url: https://charts.helm.sh/stable
  - name: nginx-stable
    url: https://helm.nginx.com/stable
  - name: jetstack
    url: https://charts.jetstack.io
  - name: harbor 
    url: https://helm.goharbor.io

releases:
  - name: nginx-ingress
    namespace: nginx-ingress
    createNamespace: true 
    chart: stable/nginx-ingress
    version: ~0.18.1
    wait: true

  # before install cert-manager you need install CRD
  # >kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/1.13.0/cert-manager.crds.yaml
  - name: cert-manager
    namespace: cert-manager
    createNamespace: true
    chart: jetstack/cert-manager
    version: ~v1.13.0
    set:
      - name: installCRDs
        value: true
    wait: true

  # create issuer for nginx-controller
  - name: chartmuseum
    namespace: chartmuseum
    createNamespace: true
    chart: stable/chartmuseum
    version: ~3.10.1
    values:
      - "../chartmuseum/values.yaml"
    wait: true

  - name: harbor
    namespace: harbor
    createNamespace: true
    chart: harbor/harbor
    version: ~1.13.0
    values:
      - "../harbor/values.yaml"
    wait: true

 
  


