apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nodeexporter
  namespace: kube-system
  labels:
    app: nodeexporter
spec:
  selector:
    matchLabels:
      app: nodeexporter
  template:
    metadata:
      name: nodeexporter
      labels:
        app: nodeexporter
    spec:
      containers:
      - name: nodeexporter
        image: quay.io/prometheus/node-exporter:latest
        ports:
          - containerPort: 9100
            hostPort: 9100
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: Exists 
        effect: "NoSchedule"
      restartPolicy: Always