apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    key: web-server
spec:
  containers:
    - name: web-server
      image: lixoi/hipster-frontend:v0.3
      volumeMounts:
        - name: app
          mountPath: /app
      env:
      - name: PORT
        value: "8080"
      - name: PRODUCT_CATALOG_SERVICE_ADDR
        value: "productcatalogservice:3550"
      - name: CURRENCY_SERVICE_ADDR
        value: "currencyservice:7000"
      - name: CART_SERVICE_ADDR
        value: "cartservice:7070"
      - name: RECOMMENDATION_SERVICE_ADDR
        value: "recommendationservice:8080"
      - name: SHIPPING_SERVICE_ADDR
        value: "shippingservice:50051"
      - name: CHECKOUT_SERVICE_ADDR
        value: "checkoutservice:5050"
      - name: AD_SERVICE_ADDR
        value: "adservice:9555"  
  initContainers:
    - name: init
      image: busybox:1.31.0
      command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
      #command: ['sh', '-c', 'echo "<!DOCTYPE html><html><head><title>Заголовок</title></head><body>"Hello World!"</body></html>" > /app/index.html']
      volumeMounts:
        - name: app
          mountPath: /app
  volumes:
    - name: app
      emptyDir: {}

